name: Prod deployment on gh pages

on:
  push:
    branches: master

jobs:
  deploy-gh:
    name: Deploy to GH pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Install and Build
        run: |
          yarn install
          yarn generate:prod
          echo "nwhacks.nwplus.io" >> dist/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
